basePath: /api
definitions:
  model.RequestStatus:
    enum:
    - pending
    - accepted
    - rejected
    type: string
    x-enum-varnames:
    - RequestPending
    - RequestAccepted
    - RequestRejected
  model.UserRole:
    enum:
    - admin
    - user
    - landlords
    - guest
    type: string
    x-enum-varnames:
    - RoleAdmin
    - RoleUser
    - RoleLandlords
    - RoleGuest
  routes.ApartmentsInput:
    properties:
      bathrooms:
        maximum: 6.5
        minimum: 0.5
        type: number
      bedroom:
        maximum: 6
        minimum: 0
        type: integer
      unit:
        maxLength: 256
        type: string
    required:
    - bathrooms
    - bedroom
    - unit
    type: object
  routes.EmailRegisteredInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  routes.LoginUserInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  routes.PropertyInput:
    properties:
      apartments:
        items:
          $ref: '#/definitions/routes.ApartmentsInput'
        type: array
      city:
        maxLength: 256
        type: string
      lat:
        type: number
      lng:
        type: number
      propertyType:
        maxLength: 256
        type: string
      state:
        maxLength: 256
        type: string
      street:
        maxLength: 512
        type: string
      unitType:
        enum:
        - single
        - multiple
        type: string
      userID:
        type: integer
      zip:
        type: integer
    required:
    - apartments
    - city
    - lat
    - lng
    - propertyType
    - state
    - street
    - unitType
    - userID
    - zip
    type: object
  routes.PropertyResponse:
    properties:
      city:
        type: string
      id:
        type: integer
      lat:
        type: number
      lng:
        type: number
      propertyType:
        type: string
      stars:
        type: integer
      state:
        type: string
      street:
        type: string
      unitType:
        type: string
      zip:
        type: integer
    type: object
  routes.RegisterUser:
    properties:
      email:
        maxLength: 265
        type: string
      firstName:
        maxLength: 265
        type: string
      lastName:
        maxLength: 265
        type: string
      password:
        maxLength: 265
        minLength: 6
        type: string
      role:
        $ref: '#/definitions/model.UserRole'
    required:
    - email
    - firstName
    - lastName
    - password
    - role
    type: object
  routes.RestPasswordInput:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  routes.RoleChangeRequest:
    properties:
      userID:
        type: integer
    required:
    - userID
    type: object
  routes.RoleChangeRequestWithUser:
    properties:
      id:
        type: integer
      newRole:
        $ref: '#/definitions/model.UserRole'
      status:
        $ref: '#/definitions/model.RequestStatus'
      userID:
        type: integer
      userName:
        type: string
    type: object
  routes.UpdateApartmentsInput:
    properties:
      ID:
        type: integer
      active:
        type: boolean
      amenities:
        items:
          type: string
        type: array
      availableOn:
        type: string
      bathrooms:
        maximum: 6.5
        minimum: 0.5
        type: number
      bedroom:
        maximum: 6
        minimum: 0
        type: integer
      deposit:
        type: number
      description:
        type: string
      images:
        items:
          type: string
        type: array
      leaseLength:
        maxLength: 256
        type: string
      rent:
        type: number
      sqFt:
        maximum: 100000000000
        type: integer
      unit:
        maxLength: 256
        type: string
    required:
    - active
    - availableOn
    - bathrooms
    - bedroom
    - deposit
    - leaseLength
    - rent
    - sqFt
    - unit
    type: object
  routes.UpdatePropertyInput:
    properties:
      amenities:
        items:
          type: string
        type: array
      apartments:
        items:
          $ref: '#/definitions/routes.UpdateApartmentsInput'
        type: array
      callingCode:
        type: string
      countryCode:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      images:
        items:
          type: string
        type: array
      includedUtilities:
        items:
          type: string
        type: array
      lastName:
        type: string
      laundryType:
        type: string
      name:
        type: string
      onMarket:
        type: boolean
      parkingFee:
        type: number
      petsAllowed:
        type: string
      phoneNumber:
        type: string
      unitType:
        enum:
        - single
        - multiple
        type: string
      website:
        type: string
    required:
    - apartments
    - email
    - laundryType
    - onMarket
    - petsAllowed
    - phoneNumber
    - unitType
    type: object
  routes.UpdateUnitsInput:
    properties:
      ID:
        type: integer
      active:
        type: boolean
      availableOn:
        type: string
      bathrooms:
        maximum: 6.5
        minimum: 0.5
        type: number
      bedrooms:
        maximum: 6
        minimum: 0
        type: integer
      sqFt:
        maximum: 100000000000
        type: integer
      unit:
        maxLength: 512
        type: string
    required:
    - active
    - availableOn
    - bathrooms
    - bedrooms
    - sqFt
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example APARTEMENTS
  version: "1.0"
paths:
  /accept-role-change-request/{id}:
    put:
      consumes:
      - application/json
      description: Accepts a role change request for an admin user
      operationId: accept-role-change-request
      parameters:
      - description: Request ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Accept a role change request
      tags:
      - Users
  /apartments/property/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a list of apartments associated with a specific property.
      parameters:
      - description: Property ID
        example: 1
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of apartments
        "500":
          description: Internal Server Error
      summary: Retrieve apartments by Property ID
      tags:
      - Apartments
    patch:
      consumes:
      - application/json
      description: Update an apartment by ID.
      parameters:
      - description: Apartment ID
        example: 1
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - default: JWT Token
        description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Apartment data to update
        in: body
        name: input
        required: true
        schema:
          items:
            $ref: '#/definitions/routes.UpdateUnitsInput'
          type: array
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Not Owner
        "500":
          description: Error
      summary: Update an apartment
      tags:
      - Apartments
  /getAllProperties:
    get:
      consumes:
      - application/json
      description: Retrieves All properties.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.PropertyResponse'
            type: array
        "500":
          description: Internal Server Error
      summary: Get All properties
      tags:
      - Property
  /getTop:
    get:
      consumes:
      - application/json
      description: Retrieves the top-rated properties in descending order.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.PropertyResponse'
            type: array
        "500":
          description: Internal Server Error
      summary: Get top-rated properties
      tags:
      - Property
  /location/autocomplete:
    get:
      consumes:
      - application/json
      description: Get location suggestions based on user input.
      parameters:
      - description: Location input for autocomplete
        in: query
        name: location
        required: true
        type: string
      - description: 'Limit the number of suggestions (default: 10)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: An array of location suggestions
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Location Autocomplete
      tags:
      - Location
  /location/search:
    get:
      consumes:
      - application/json
      description: Search for locations based on user input.
      parameters:
      - description: Location input for search
        in: query
        name: location
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: An array of location search results
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Location Search
      tags:
      - Location
  /manage-role-requests:
    get:
      consumes:
      - application/json
      description: Retrieves All user requests to change role.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/routes.RoleChangeRequestWithUser'
            type: array
        "403":
          description: Only admins can manage role change requests
        "500":
          description: Internal Server Error
      summary: Manage All users requests
      tags:
      - Users
  /property:
    post:
      consumes:
      - application/json
      description: Create a new property listing.
      parameters:
      - default: JWT Token
        description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Property data to create
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/routes.PropertyInput'
      produces:
      - application/json
      responses:
        "200":
          description: Property created successfully
        "400":
          description: 'Validation Error" Example({"message": "Validation Error'
        "401":
          description: 'Unauthorized" Example({"message": "Unauthorized'
        "500":
          description: 'Internal Server Error" Example({"message": "Internal Server
            Error'
      summary: Create a property
      tags:
      - Property
  /property/delete/{id}:
    delete:
      description: Deletes a property by ID.
      operationId: delete-property
      parameters:
      - description: Property ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Delete a property
      tags:
      - Property
  /property/update/{id}:
    put:
      consumes:
      - application/json
      description: Update a property by ID.
      parameters:
      - description: Property ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      - default: JWT Token
        description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Property data to update
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/routes.UpdatePropertyInput'
      - description: Property image to upload
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: UPDATED SUCCCESS
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update a property
      tags:
      - Property
  /reject-role-request/{id}:
    put:
      consumes:
      - application/json
      description: Rejects a role change request for an admin user
      operationId: reject-role-change-request
      parameters:
      - description: Request ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Reject a role change request
      tags:
      - Users
  /submit-role-change:
    post:
      consumes:
      - application/json
      description: Submit user request to change role.
      parameters:
      - description: User Submit
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.RoleChangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: THE REQUEST HAS BEEN SUBMITED SUCCESSFULLY
        "400":
          description: Invalid input
        "500":
          description: You can only request a role change for yourself
      summary: Submit Change Role Request.
      tags:
      - Users
  /user/forget-password:
    post:
      consumes:
      - application/json
      description: Sends a password reset email to the user's registered email address.
      parameters:
      - description: User's registered email address
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/routes.EmailRegisteredInput'
      produces:
      - application/json
      responses:
        "200":
          description: Email sent successfully
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: 'Invalid Email" Example({"message": "Invalid Email'
        "401":
          description: 'Social Login Account" Example({"message": "Social Login Account'
        "500":
          description: 'Internal Server Error" Example({"message": "Internal Server
            Error'
      summary: Send password reset email
      tags:
      - Users
  /user/login:
    post:
      consumes:
      - application/json
      description: Logs in a user using their email and password.
      parameters:
      - description: User login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/routes.LoginUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: User login successful
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'Validation Error" Example({"message": "Validation Error'
        "401":
          description: 'Unauthorized" Example({"message": "Unauthorized'
        "500":
          description: 'Internal Server Error" Example({"message": "Internal Server
            Error'
      summary: Log in user
      tags:
      - Users
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided information.
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.RegisterUser'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/routes.RegisterUser'
        "400":
          description: Invalid input
        "409":
          description: User already exists
      summary: Register a new user
      tags:
      - Users
  /user/reset-password:
    post:
      consumes:
      - application/json
      description: Resets a user's password using a reset token.
      parameters:
      - description: New password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/routes.RestPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: Password reset successfully
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: 'Validation Error" Example({"message": "Validation Error'
        "401":
          description: 'Unauthorized" Example({"message": "Unauthorized'
        "500":
          description: 'Internal Server Error" Example({"message": "Internal Server
            Error'
      summary: Reset user password
      tags:
      - Users
swagger: "2.0"
